# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI

on:
  push:
    branches: [ main, feature-test ]
  pull_request:
    branches: [ main, feature-test ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test


# # https://blog.devgenius.io/learn-ci-cd-with-github-actions-to-deploy-a-nestjs-app-to-heroku-8feb715d3ce7
# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# name: Node.js CI
# on:
#   push:
#     branches: [ main, feature-test ]
#   pull_request:
#     branches: [ main, feature-test ]
# jobs:
#   do-the-thing--build-it:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: 16.x
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
#     steps:
#         - uses: actions/checkout@v2
#         - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'
#         - run: npm ci
#         - run: npm run build --if-present
#         - run: npm test
        
      
# https://codememoirs.com/automatic-deployment-digitalocean-github-actions
# name: Continuous Integration

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   merge_pull_request:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout main branch
#         uses: actions/checkout@v2

#       - name: Use Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: '16.x'

#       - name: Install dependencies
#         run: npm install

#       - name: Test application
#         run: npm test

#       - name: Build application
#         run: npm run build